/** 38px — legacy Query Tool control height. */
const height = 'h-9.5 min-h-9.5';

const fieldLabel =
  'min-h-5 text-body-sm font-medium leading-snug text-pretty text-foreground';

/** Chip remove control — plain PrimeIcon (replaces default times-circle SVG). */
const chipRemoveIcon = 'pi pi-times';

export const AreaSearchControlStyles = {
  chipRemoveIcon,
  fieldLabel,
  input: `box-border w-full text-body-sm leading-5 ${height}`,
  select: [
    'w-full min-w-0',
    height,
    '[&_.p-select-label]:flex [&_.p-select-label]:items-center',
    '[&_.p-select-label]:min-h-[calc(2.375rem-2px)] [&_.p-select-label]:px-2.5',
    '[&_.p-select-label]:text-sm! [&_.p-select-label]:leading-5',
    '[&_.p-select-dropdown]:w-8'
  ].join(' '),
  multiSelect: [
    'w-full text-body-sm',
    height,
    '[&_.p-multiselect-label]:flex [&_.p-multiselect-label]:items-center',
    '[&_.p-multiselect-label]:min-h-[calc(2.375rem-2px)]',
    '[&_.p-multiselect-label-container]:min-h-[calc(2.375rem-2px)]',
    '[&_.p-multiselect-dropdown]:w-8',
    '[&_.p-multiselect-chip]:hidden [&_.p-multiselect-chip-item]:hidden'
  ].join(' '),
  selectPanel: [
    '[&_.p-select-option]:text-body-sm [&_.p-select-option]:px-2.5 [&_.p-select-option]:py-1.5',
    '[&_.p-select-option.p-select-option-selected]:bg-primary/10 [&_.p-select-option.p-select-option-selected]:text-primary'
  ].join(' '),
  multiSelectPanel: [
    '[&_.p-multiselect-option>.p-checkbox]:hidden! [&_.p-multiselect-option>p-checkbox]:hidden!',
    '[&_.p-multiselect-option]:gap-0 [&_.p-multiselect-option]:text-body-sm',
    '[&_.p-multiselect-option]:px-2.5 [&_.p-multiselect-option]:py-1.5',
    '[&_.p-multiselect-option.p-multiselect-option-selected]:bg-primary/10',
    '[&_.p-multiselect-option.p-multiselect-option-selected]:text-primary',
    '[&_.p-multiselect-option[data-p-highlight=true]]:bg-primary/10',
    '[&_.p-multiselect-option[data-p-highlight=true]]:text-primary'
  ].join(' '),
  treeMultiSelect: [
    'w-full text-body-sm',
    'min-h-9.5',
    '[&_.p-multiselect-label-container]:flex [&_.p-multiselect-label-container]:min-h-[calc(2.375rem-2px)]',
    '[&_.p-multiselect-label-container]:flex-wrap [&_.p-multiselect-label-container]:items-center [&_.p-multiselect-label-container]:gap-1',
    '[&_.p-multiselect-label-container]:py-1 [&_.p-multiselect-label-container]:pl-2',
    '[&_.p-multiselect-label]:flex [&_.p-multiselect-label]:min-h-[calc(2.375rem-2px)]',
    '[&_.p-multiselect-label]:flex-wrap [&_.p-multiselect-label]:items-center [&_.p-multiselect-label]:gap-1',
    '[&_.p-multiselect-dropdown]:w-8 [&_.p-multiselect-dropdown]:self-start [&_.p-multiselect-dropdown]:mt-2',
    '[&_.p-multiselect-chip-item]:flex [&_.p-multiselect-chip-item]:items-center',
    '[&_.p-multiselect-chip]:flex [&_.p-multiselect-chip]:items-center [&_.p-multiselect-chip]:gap-1',
    '[&_.p-multiselect-chip]:rounded-md [&_.p-multiselect-chip]:border [&_.p-multiselect-chip]:border-border',
    '[&_.p-multiselect-chip]:bg-surface [&_.p-multiselect-chip]:text-caption [&_.p-multiselect-chip]:text-foreground',
    '[&_.p-chip-label]:flex [&_.p-chip-label]:items-center [&_.p-chip-label]:leading-snug',
    '[&_.p-chip-remove-icon]:flex! [&_.p-chip-remove-icon]:items-center! [&_.p-chip-remove-icon]:justify-center!',
    '[&_.p-chip-remove-icon]:size-[1em]! [&_.p-chip-remove-icon]:min-w-0! [&_.p-chip-remove-icon]:min-h-0!',
    '[&_.p-chip-remove-icon]:self-center [&_.p-chip-remove-icon]:shrink-0 [&_.p-chip-remove-icon]:rounded-none!',
    '[&_.p-chip-remove-icon]:text-[0.65rem]! [&_.p-chip-remove-icon]:leading-none!',
    '[&_.p-chip-remove-icon]:text-subtle hover:[&_.p-chip-remove-icon]:text-foreground'
  ].join(' '),
  treeMultiSelectPanel: [
    '[&_.p-multiselect-option>.p-checkbox]:hidden! [&_.p-multiselect-option>p-checkbox]:hidden!',
    '[&_.p-multiselect-option]:gap-0 [&_.p-multiselect-option]:text-body-sm',
    '[&_.p-multiselect-option]:px-2.5 [&_.p-multiselect-option]:py-1.5',
    '[&_.p-multiselect-option.p-multiselect-option-selected]:bg-primary/10',
    '[&_.p-multiselect-option.p-multiselect-option-selected]:text-primary',
    '[&_.p-multiselect-option[data-p-highlight=true]]:bg-primary/10',
    '[&_.p-multiselect-option[data-p-highlight=true]]:text-primary',
    '[&_.p-multiselect-option-group]:px-2.5 [&_.p-multiselect-option-group]:pt-2',
    '[&_.p-multiselect-option-group-label]:text-xs [&_.p-multiselect-option-group-label]:font-semibold',
    '[&_.p-multiselect-option-group-label]:uppercase [&_.p-multiselect-option-group-label]:text-subtle'
  ].join(' '),
  oafAccordion: [
    '[&_.p-accordionpanel]:overflow-hidden [&_.p-accordionpanel]:rounded-md',
    '[&_.p-accordionpanel]:border [&_.p-accordionpanel]:border-border',
    '[&_.p-accordionheader]:px-3 [&_.p-accordionheader]:py-3',
    '[&_.p-accordionheader]:bg-primary/10 [&_.p-accordionheader]:hover:bg-primary/20',
    '[&_.p-accordionheader]:font-medium [&_.p-accordionheader]:leading-5'
  ].join(' '),
  /** Premier / warning note accordion — semantic warning tokens. */
  premierNoteAccordion: [
    '[&_.p-accordionpanel]:overflow-hidden [&_.p-accordionpanel]:rounded',
    '[&_.p-accordionpanel]:border [&_.p-accordionpanel]:border-warning/30',
    '[&_.p-accordionpanel]:bg-warning/10!',
    '[&_.p-accordionpanel[data-p-active="true"]_.p-accordionheader]:border-b',
    '[&_.p-accordionpanel[data-p-active="true"]_.p-accordionheader]:border-warning/30',
    '[&_.p-accordionpanel:not([data-p-active="true"])_.p-accordionheader]:border-b-0!',
    '[&_.p-accordionpanel:not([data-p-active="true"])_.p-accordionheader]:rounded-b',
    '[&_.p-accordionheader]:bg-transparent! [&_.p-accordionheader]:px-3',
    '[&_.p-accordionheader]:py-2 [&_.p-accordionheader]:text-body-sm',
    '[&_.p-accordionheader]:font-semibold [&_.p-accordionheader]:text-warning!',
    '[&_.p-accordionheader_.p-accordionheader-toggle-icon]:text-warning!',
    '[&_.p-accordioncontent]:bg-transparent! [&_.p-accordioncontent]:px-3',
    '[&_.p-accordioncontent[data-p-active="true"]]:pt-3 [&_.p-accordioncontent[data-p-active="true"]]:pb-4',
    '[&_.p-accordioncontent]:text-warning!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:h-0!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:min-h-0!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:overflow-hidden!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:p-0!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:m-0!',
    '[&_.p-accordioncontent:not([data-p-active="true"])_.p-motion]:hidden!',
    '**:[[class*="accordioncontent-content-wrapper"]]:bg-transparent!',
    '**:[[class*="accordioncontent-content-wrapper"]]:[background-color:transparent!important]',
    '**:[[class*="accordioncontent-content"]]:bg-transparent!',
    '**:[[class*="accordioncontent-content"]]:[background-color:transparent!important]',
    '**:[[class*="accordioncontent-content"]]:p-0!',
    '**:[[class*="accordioncontent-content"]]:text-inherit!',
    '**:[[class*="accordioncontent-content"]]:shadow-none!',
    '[&_.p-accordioncontent]:[background-color:transparent!important]',
    '[&_.p-accordioncontent_.p-motion]:bg-transparent!',
    '[&_.p-accordioncontent_p]:bg-transparent [&_.p-accordioncontent_div]:bg-transparent'
  ].join(' '),
  /** Danger note accordion — semantic danger tokens. */
  dangerNoteAccordion: [
    '[&_.p-accordionpanel]:overflow-hidden [&_.p-accordionpanel]:rounded',
    '[&_.p-accordionpanel]:border [&_.p-accordionpanel]:border-danger/30',
    '[&_.p-accordionpanel]:bg-danger/10!',
    '[&_.p-accordionpanel[data-p-active="true"]_.p-accordionheader]:border-b',
    '[&_.p-accordionpanel[data-p-active="true"]_.p-accordionheader]:border-danger/30',
    '[&_.p-accordionpanel:not([data-p-active="true"])_.p-accordionheader]:border-b-0!',
    '[&_.p-accordionpanel:not([data-p-active="true"])_.p-accordionheader]:rounded-b',
    '[&_.p-accordionheader]:bg-transparent! [&_.p-accordionheader]:px-3',
    '[&_.p-accordionheader]:py-2 [&_.p-accordionheader]:text-body-sm',
    '[&_.p-accordionheader]:font-semibold [&_.p-accordionheader]:text-danger!',
    '[&_.p-accordionheader_.p-accordionheader-toggle-icon]:text-danger!',
    '[&_.p-accordioncontent]:bg-transparent! [&_.p-accordioncontent]:px-3',
    '[&_.p-accordioncontent[data-p-active="true"]]:pt-3 [&_.p-accordioncontent[data-p-active="true"]]:pb-4',
    '[&_.p-accordioncontent]:text-danger!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:h-0!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:min-h-0!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:overflow-hidden!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:p-0!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:m-0!',
    '[&_.p-accordioncontent:not([data-p-active="true"])_.p-motion]:hidden!',
    '**:[[class*="accordioncontent-content-wrapper"]]:bg-transparent!',
    '**:[[class*="accordioncontent-content-wrapper"]]:[background-color:transparent!important]',
    '**:[[class*="accordioncontent-content"]]:bg-transparent!',
    '**:[[class*="accordioncontent-content"]]:[background-color:transparent!important]',
    '**:[[class*="accordioncontent-content"]]:p-0!',
    '**:[[class*="accordioncontent-content"]]:text-inherit!',
    '**:[[class*="accordioncontent-content"]]:shadow-none!',
    '[&_.p-accordioncontent]:[background-color:transparent!important]',
    '[&_.p-accordioncontent_.p-motion]:bg-transparent!',
    '[&_.p-accordioncontent_p]:bg-transparent [&_.p-accordioncontent_div]:bg-transparent'
  ].join(' '),
  contactPricingAccordion: [
    '[&_.p-accordionpanel]:overflow-hidden [&_.p-accordionpanel]:rounded-md [&_.p-accordionpanel]:border [&_.p-accordionpanel]:border-warning/30',
    '[&_.p-accordionpanel:not([data-p-active="true"])]:bg-warning/10!',
    '[&_.p-accordionpanel[data-p-active="true"]]:bg-surface!',
    '[&_.p-accordionpanel[data-p-active="true"]_.p-accordionheader]:border-b [&_.p-accordionpanel[data-p-active="true"]_.p-accordionheader]:border-warning/30',
    '[&_.p-accordionpanel:not([data-p-active="true"])_.p-accordionheader]:border-b-0!',
    '[&_.p-accordionpanel:not([data-p-active="true"])_.p-accordionheader]:rounded-b',
    '[&_.p-accordionheader]:bg-warning/10! [&_.p-accordionheader]:px-4 [&_.p-accordionheader]:py-2',
    '[&_.p-accordionheader]:text-body-sm [&_.p-accordionheader]:font-medium [&_.p-accordionheader]:text-foreground!',
    '[&_.p-accordionheader_.p-accordionheader-toggle-icon]:text-subtle!',
    '[&_.p-accordioncontent]:bg-surface!',
    '[&_.p-accordioncontent]:text-foreground!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:h-0!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:min-h-0!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:overflow-hidden!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:p-0!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:m-0!',
    '[&_.p-accordioncontent:not([data-p-active="true"])_.p-motion]:hidden!',
    '[&_.p-accordioncontent_.p-motion]:bg-surface!'
  ].join(' '),
  contactDncAccordion: [
    '[&_.p-accordionpanel]:overflow-hidden [&_.p-accordionpanel]:rounded-md [&_.p-accordionpanel]:border [&_.p-accordionpanel]:border-danger/30',
    '[&_.p-accordionpanel:not([data-p-active="true"])]:bg-danger/10!',
    '[&_.p-accordionpanel[data-p-active="true"]]:bg-surface!',
    '[&_.p-accordionpanel[data-p-active="true"]_.p-accordionheader]:border-b [&_.p-accordionpanel[data-p-active="true"]_.p-accordionheader]:border-danger/30',
    '[&_.p-accordionpanel:not([data-p-active="true"])_.p-accordionheader]:border-b-0!',
    '[&_.p-accordionpanel:not([data-p-active="true"])_.p-accordionheader]:rounded-b',
    '[&_.p-accordionheader]:bg-danger/10! [&_.p-accordionheader]:px-4 [&_.p-accordionheader]:py-2',
    '[&_.p-accordionheader]:text-body-sm [&_.p-accordionheader]:font-medium [&_.p-accordionheader]:text-danger!',
    '[&_.p-accordionheader_.p-accordionheader-toggle-icon]:text-danger!',
    '[&_.p-accordioncontent]:bg-surface!',
    '[&_.p-accordioncontent]:text-danger!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:h-0!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:min-h-0!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:overflow-hidden!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:p-0!',
    '[&_.p-accordioncontent:not([data-p-active="true"])]:m-0!',
    '[&_.p-accordioncontent:not([data-p-active="true"])_.p-motion]:hidden!',
    '[&_.p-accordioncontent_.p-motion]:bg-surface!'
  ].join(' ')
} as const;
